#+title: MTR
#+ABSTRACT: MTR combines the functionality of the traceroute and ping programs in a single network diagnostic tool

* MTR

[[http://www.bitwizard.nl/mtr/][MTR]] combines the functionality of the 'traceroute' and 'ping' programs in a
single network diagnostic tool. It is a tool which enables to diagnose and
identify networking errors along with network status reports.

MTR uses the Internet Control Message Protocol (ICMP) to to test traffic between
two points on the Internet.

MTR may not detect errors from one direction when there is still packet loss
from the opposite direction.

Hops are the Internet nodes that packets pass through to get to their
destination.

** Generate a MTR Report

#+begin_src bash
mtr -rw <destination>
#+end_src

Run faster interval:

#+begin_src bash
mtr -rwc 50 -i 0.2 -rw <destination>
#+end_src

+ ~-r~ - generate the report
+ ~-w~ - use the long-version of the hostname
+ ~-c~ - set how many packets are sent and recorded in the report
+ ~-i~ - run the report at a faster rate to reveal packet loss that can occur
  only during network congestion

** Read a MTR Report

Each numbered line in the MTR report is a hop.

+ ~Loss%~ - the percentage of packet loss at each hop
+ ~Snt~ - the number of packets sent.
