#+title: Pi Hole

* Pi Hole

Pi Hole is a network-wide ad blocker. It can remove almost all ads on all
devices without having to install an adblocker on each of these devices.

Pi Hole provides a DNS Server for all requests. Pi-Hole is place in between a
device and the DNS server so that it blocks out any requests to known ad
servers.

Pi Hole blocks ads on any device including the ones that do not allow you to
make any modifications. It also reduces the bandwidth and it improves overall
network performance.

$2 to $5 in electricity cost for the whole year to keep the Pi running 24/7.

Pi Hole can work with the WiFi, but a wired connection is better for reliability
as DNS requests will depend on this.

Enable SSH by creating an empty file called ~ssh~ in the root folder on the SD
card.

Additionally, set fixed IP for the Pi Hole device.

#+begin_src bash
wget -O basic-install.sh https://install.pi-hole.net
sudo bash basic-install.sh
#+end_src

PiHole has DHCP capabilities, which means it can act as your DHCP server and
assign IP addresses to your clients. However, most routers can do this well as
well. Therefore, we are going to let your router handle that and not use
PiHole’s DHCP server.

** Pi Hole Commands

*** Pi Hole: Change Web Panel Password

#+begin_src bash
pihole -a -p
#+end_src

*** Pi Hole: Status, Realtime log and Statistics

#+begin_src bash
pihole status
pihole -t tail log
pihole -c
#+end_src
*** Pi Hole: Whitelist and Blacklist

List whitelisted domains:

#+begin_src bash
pihole -w -l
#+end_src

Add a domain to the whitelist:

#+begin_src bash
pihole -w example.com
#+end_src

Remove a domain from the whitelist:

#+begin_src bash
pihole -w -d example.com
#+end_src

List blacklisted domains:

#+begin_src bash
pihole -b -l
#+end_src

Add a domain to the blacklist:

#+begin_src bash
pihole -b example.com
#+end_src

Remove a domain from the blacklist:

#+begin_src bash
pihole -b -d example.com
#+end_src
*** Pi Hole: Update

#+begin_src bash
pihole -up
#+end_src
*** Pi Hole: Query Logging

Turn query logging on:

#+begin_src bash
pihole -l on
#+end_src

Turn query logging off:

#+begin_src bash
pihole -l off
#+end_src
*** Pi Hole: Enable & Disable

#+begin_src bash
pihole enable
pihole disable
pihole disable 10m
pihole disable 60s
#+end_src

** Move Query Logging to RAM

Extensive writing can damage SD card. Move your logs to RAM instead of SD card.

https://github.com/azlux/log2ram
